<a href="https://colab.research.google.com/github/hepuliu/deep_learning/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

In [56]:
# Import Libraries
import keras
import numpy as np
import pandas as pd
import tensorflow as tf

# Data Processing

In [57]:
# Import Dataset
from google.colab import drive
drive.mount

dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/Course_DL/Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [58]:
print (x)
print (y)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [59]:
# Label Encoding the "Gender" Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2])
print (x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [60]:
# Label Encoding the "Country" Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print (x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [61]:
 # Split Dataset into Training and Test sets
 from sklearn.model_selection import train_test_split
 x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [62]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# Constructing ANN

In [63]:
# Initialization
ann = tf.keras.models.Sequential()

# Add input layer and the hidden layers
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Add output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Training ANN

In [64]:
# Compile the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on Training Set
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5966 - accuracy: 0.7216
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4732 - accuracy: 0.7986
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4483 - accuracy: 0.8014
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4389 - accuracy: 0.8033
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4339 - accuracy: 0.8058
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4304 - accuracy: 0.8075
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4276 - accuracy: 0.8120
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4250 - accuracy: 0.8139
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4224 - accuracy: 0.8186
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4192 - accura

# Making Prediction

In [65]:
print (ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


# Predicting Test Set Results

In [66]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
