<a href="https://colab.research.google.com/github/hepuliu/deep_learning/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

In [43]:
# Import Libraries
import keras
import numpy as np
import pandas as pd
import tensorflow as tf

# Data Processing

In [44]:
# Import Dataset
from google.colab import drive
drive.mount

dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/Course_DL/Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [45]:
print (x)
print (y)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [46]:
# Label Encoding the "Gender" Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2])
print (x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [47]:
# Label Encoding the "Country" Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print (x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [48]:
 # Split Dataset into Training and Test sets
 from sklearn.model_selection import train_test_split
 x_train, x_test, y_train, y_split = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [49]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# Constructing ANN

In [50]:
# Initialization
ann = tf.keras.models.Sequential()

# Add input layer and the hidden layers
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Add output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Training ANN

In [51]:
# Compile the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the ANN on Training Set
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6223 - accuracy: 0.7005
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4887 - accuracy: 0.7971
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4609 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4457 - accuracy: 0.7980
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4364 - accuracy: 0.8026
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4283 - accuracy: 0.8083
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4186 - accuracy: 0.8217
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4081 - accuracy: 0.8316
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3992 - accuracy: 0.8349
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3906 - accura